#!/usr/bin/env python3
"""
render_glyphs_from_db.py

Read a glyphs_{w}_{h}.db generated by create_glyph_db.py and render PNG images
and metadata CSVs, grouped into "score_X" folders (score = number of symmetries true).

Configuration is near the top for SCALE and MARGIN. You can optionally provide a
SQL WHERE clause to restrict which glyphs to render.
"""

import sqlite3
from pathlib import Path
from PIL import Image
import csv
import os

# ---------------------------
# CONFIG
# ---------------------------
DB_PATH = Path("dbs") / "glyphs_5_5.db"  # set to the DB you created
if not DB_PATH.exists():
	raise SystemExit(f"Database not found: {DB_PATH} -- create it first with create_glyph_db.py")
OUT_BASE = Path("glyphs") / "5x5_from_db"  # top-level output folder
SCALE = 20
MARGIN = 1  # in cells
# Optional SQL WHERE clause (string). Examples:
#   "horizontal=1"  -> only horizontally symmetric glyphs
#   "filled>=12 AND score>=2"
#   None or "" -> select everything
WHERE_CLAUSE = ""  # e.g. "horizontal=1"


# ---------------------------

# helper to read meta of DB for width/height
def read_db_meta(conn):
	cur = conn.cursor()
	try:
		cur.execute("SELECT v FROM meta WHERE k='w'")
		w = int(cur.fetchone()[0])
		cur.execute("SELECT v FROM meta WHERE k='h'")
		h = int(cur.fetchone()[0])
	except Exception:
		# fallback to inferring from bitstring length of first row
		cur.execute("SELECT bitstring FROM glyphs LIMIT 1")
		row = cur.fetchone()
		if not row:
			raise RuntimeError("DB empty or corrupt and no meta table")
		bitlen = len(row[0])
		# try square
		side = int(bitlen ** 0.5)
		w = h = side
	return w, h


def grid_from_bitstring(bs, w, h):
	bits = [1 if ch == "1" else 0 for ch in bs]
	return [[bits[r * w + c] for c in range(w)] for r in range(h)]


def render_grid_to_png(grid, scale, margin, out_path):
	h = len(grid)
	w = len(grid[0])
	size_px = (w + 2 * margin) * scale, (h + 2 * margin) * scale
	img = Image.new("RGB", size_px, (255, 255, 255))
	px = img.load()
	for r in range(h):
		for c in range(w):
			if grid[r][c]:
				x0 = (c + margin) * scale
				y0 = (r + margin) * scale
				for dx in range(scale):
					for dy in range(scale):
						px[x0 + dx, y0 + dy] = (0, 0, 0)
	out_path.parent.mkdir(parents=True, exist_ok=True)
	img.save(str(out_path))


def main():
	conn = sqlite3.connect(str(DB_PATH))
	cur = conn.cursor()
	w, h = read_db_meta(conn)
	print(f"Rendering glyphs from DB {DB_PATH} (size {w}x{h})")

	# prepare out folders
	OUT_BASE.mkdir(parents=True, exist_ok=True)
	for k in range(7):
		(OUT_BASE / f"score_{k}" / "images").mkdir(parents=True, exist_ok=True)

	# prepare CSV writers
	master_csv_path = OUT_BASE / "metadata.csv"
	master_f = open(master_csv_path, "w", newline="")
	mw = csv.writer(master_f)
	mw.writerow(["id", "int_repr", "bitstring", "filled", "components", "score", "filename"])

	bucket_files = {}
	bucket_writers = {}
	for k in range(7):
		bf = open(OUT_BASE / f"score_{k}" / "metadata.csv", "w", newline="")
		bw = csv.writer(bf)
		bw.writerow(["id", "int_repr", "bitstring", "filled", "components", "filename"])
		bucket_files[k] = bf
		bucket_writers[k] = bw

	# Build SELECT
	where = WHERE_CLAUSE.strip()
	if where:
		query = f"SELECT id, bitstring, int_repr, filled, components, horizontal, vertical, diag1, diag2, rot90, rot180 FROM glyphs WHERE {where} ORDER BY id"
	else:
		query = "SELECT id, bitstring, int_repr, filled, components, horizontal, vertical, diag1, diag2, rot90, rot180 FROM glyphs ORDER BY id"

	cur.execute(query)
	rows = cur.fetchall()
	print(f"Selected {len(rows)} glyphs to render.")

	for row in rows:
		gid, bitstring, intrepr, filled, components, h_sym, v_sym, d1, d2, r90, r180 = row
		# compute score as in your original
		score = int(h_sym) + int(v_sym) + int(d1) + int(d2) + int(r90) + int(r180)
		fname = f"{bitstring}.png"
		img_path = OUT_BASE / f"score_{score}" / "images" / fname

		# render image
		grid = grid_from_bitstring(bitstring, w, h)
		render_grid_to_png(grid, SCALE, MARGIN, img_path)

		# write metadata
		rel_path = f"score_{score}/images/{fname}"
		mw.writerow([gid, intrepr, bitstring, filled, components, score, rel_path])
		bucket_writers[score].writerow([gid, intrepr, bitstring, filled, components, f"images/{fname}"])

	# close files
	master_f.close()
	for f in bucket_files.values():
		f.close()
	conn.close()
	print("Rendering done. Master CSV:", master_csv_path)
	print("Buckets in:", OUT_BASE)


if __name__ == "__main__":
	main()
